apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-kubewiki
  namespace: kubewiki
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubewiki-service
            port:
              number: 80