apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubewiki-pv
  namespace: kubewiki
  labels:
    app: kubewiki
    storage: padrao
spec: 
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
  storageClassName: standard