apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubewiki-pvc
  namespace: kubewiki
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  selector:
    matchLabels:
      storage: padrao