apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
  namespace: kubewiki
  labels:
    app: kubewiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewiki
  template:
    metadata:
      name: kubewiki
      namespace: kubewiki
      labels:
        app: kubewiki
    spec:
      containers:
      - name: kubewiki
        image: fabiomfrade/kubewiki:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP
            name: http
        resources:
          requests:
            cpu: "0.2"
            memory: 64Mi
          limits:
            cpu: "0.5"
            memory: 128Mi
        startupProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 3
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: nginx-kubewiki
          mountPath: /etc/nginx/http.d/default.conf
          subPath: default.conf
        - name: kubewiki-data
          mountPath: /var/www/localhost/htdocs/dokuwiki

      volumes:
      - name: nginx-kubewiki
        configMap:
          name: nginx-config
      - name: kubewiki-data
        persistentVolumeClaim:
          claimName: kubewiki-pvc