apiVersion: v1
kind: Service
metadata:
  name: kubewiki-service
  namespace: kubewiki
  labels:
    app: kubewiki
spec:
  selector:
    app: kubewiki
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: metrics

# apiVersion: v1
# kind: Service
# metadata:
#   name: kubewiki-metrics-svc
#   namespace: kubewiki
#   labels:
#     app: kubewiki
# spec:
#   ports:
#   - port: 9113
#     name: metrics
#   selector:
#     app: kubewiki