apiVersion: v1
kind: Service
metadata:
  name: kubewiki-svc-lb
  namespace: kubewiki
spec:
  type: LoadBalancer
  selector:
    app: kubewiki
  ports:
  - port: 80
    name: http
  - port: 9113
    name: metrics
