apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kubevpa
  namespace: kubewiki
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: kubedeploy
  updatePolicy:
    updateMode: "Off"